[pytest]
filterwarnings =
    ignore:The anyio\.abc\.BlockingPortal alias is deprecated.*:DeprecationWarning:starlette\.testclient
    error:Using `httpx` with `starlette\.testclient` is deprecated.*:Warning
